language: elixir
elixir:
  - 1.11.0
otp_release:
  - 23.0.4
before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - export CI="true"
script:
  - bin/test
after_script:
  - MIX_ENV=test mix inch.report
addons:
  postgresql: "9.4"
